
import { TaskCategory } from './types'; // Need to import TaskCategory here

export const POINTS_PER_DOLLAR = 1_000_000; // 1 USD = 1,000,000 points

// Ad Task Definitions (from TasksScreen.tsx)
export const TOTAL_INTERSTITIAL_ADS = 1080;
export const INTERSTITIAL_BATCH_SIZE = 180;
export const TOTAL_POP_ADS_DAILY = 1200;
export const POP_ADS_BATCH_SIZE = 150;
export const TOTAL_VISIT_ADS_DAILY = 720;
export const VISIT_ADS_BATCH_SIZE = 360;
export const TOTAL_WEBSITE_ADS_DAILY = 620;
export const WEBSITE_ADS_BATCH_SIZE = 180;
export const TOTAL_EXTRA_ADS_DAILY = 180;
export const EXTRA_ADS_BATCH_SIZE = 60;

// Auto Ads Configuration (from previous request)
export const AUTO_ADS_INTERVAL_MS = 16000; // Auto show ad every 16 seconds
// User requested 0.0002 per ad. Assuming 0.0002 USD = 0.0002 * 1,000,000 points = 200 points.
export const AUTO_ADS_REWARD_POINTS = 200; // Points per auto ad
export const AUTO_ADS_DAILY_LIMIT = 300; // Max auto ads per day
export const AUTO_ADS_COOLDOWN_AFTER_CLAIM_MS = 60 * 60 * 1000; // 1 hour cooldown after completing 300 auto ads

// Daily Check-in Configuration
export const DAILY_CHECKIN_REWARDS = [25, 50, 75, 100, 125, 200]; // Points for Day 1 to Day 6
export const DAILY_CHECKIN_SURPRISE_BOX_REWARD = 1500; // Points for Day 7

// Spin Wheel Configuration
export const MAX_SPINS_PER_DAY = 10;
export const SPIN_AD_URL = 'https://viikqoye.com/dc/?blockID=398500'; // Ad URL for spin wheel

// Withdrawal Configuration
export const WITHDRAWAL_AMOUNTS = [5, 10, 25, 50, 100];
export const MIN_WITHDRAWAL_BALANCE = 5; // Minimum withdrawal is $5

// Profile Edit Cooldowns
export const PROFILE_EDIT_NAME_COOLDOWN_MS = 7 * 24 * 60 * 60 * 1000; // 7 days
export const PROFILE_EDIT_EMAIL_COOLDOWN_MS = 30 * 24 * 60 * 60 * 1000; // 30 days

// UI Colors
export const AVAILABLE_COLORS = [
  { name: 'Primary', class: 'bg-primary' },
  { name: 'Secondary', class: 'bg-secondary' },
  { name: 'Accent', class: 'bg-accent' },
  { name: 'Success', class: 'bg-success' },
  { name: 'Warning', class: 'bg-warning' },
  { name: 'Error', class: 'bg-error' },
  { name: 'Blue', class: 'bg-blue-500' },
  { name: 'Purple', class: 'bg-purple-500' },
  { name: 'Pink', class: 'bg-pink-500' },
  { name: 'Indigo', class: 'bg-indigo-500' },
];

export const INITIAL_CATEGORIES: TaskCategory[] = [
  {
    id: 'inter',
    title: 'Interstitial Ads',
    color: 'bg-primary',
    tasks: Array.from({ length: TOTAL_INTERSTITIAL_ADS }).map((_, i) => ({
      id: `inter-${i + 1}`,
      name: `Interstitial Ad ${i + 1}`,
      description: 'View a full-screen advertisement',
      time: 15,
      reward: 100,
      status: 'pending',
      image: '',
    })),
  },
  {
    id: 'pop',
    title: 'Pop Ads',
    color: 'bg-accent',
    tasks: Array.from({ length: TOTAL_POP_ADS_DAILY }).map((_, i) => ({
      id: `pop-${i + 1}`,
      name: `Pop Ad ${i + 1}`,
      description: 'Interact with a pop-up advertisement',
      time: 10,
      reward: 75,
      status: 'pending',
      image: '',
    })),
  },
  {
    id: 'visit',
    title: 'Visit Ads',
    color: 'bg-secondary',
    tasks: Array.from({ length: TOTAL_VISIT_ADS_DAILY }).map((_, i) => ({
      id: `visit-${i + 1}`,
      name: `Visit Ad ${i + 1}`,
      description: 'Visit a sponsored website',
      time: 20,
      reward: 120,
      status: 'pending',
      image: '',
    })),
  },
  {
    id: 'website',
    title: 'Website Ads',
    color: 'bg-success',
    tasks: Array.from({ length: TOTAL_WEBSITE_ADS_DAILY }).map((_, i) => ({
      id: `website-${i + 1}`,
      name: `Website Ad ${i + 1}`,
      description: 'Browse a website for a short period',
      time: 25,
      reward: 150,
      status: 'pending',
      image: '',
    })),
  },
  {
    id: 'extra',
    title: 'Extra Ads',
    color: 'bg-purple-500',
    tasks: Array.from({ length: TOTAL_EXTRA_ADS_DAILY }).map((_, i) => ({
      id: `extra-${i + 1}`,
      name: `Extra Ad ${i + 1}`,
      description: 'Special high-reward advertisement',
      time: 30,
      reward: 200,
      status: 'pending',
      image: '',
    })),
  },
  {
    id: 'ai-generated',
    title: 'AI Generated Tasks',
    color: 'bg-blue-500',
    tasks: [], // Tasks will be generated by AI dynamically
  },
  {
    id: 'auto',
    title: 'Auto Ads',
    color: 'bg-red-500',
    tasks: Array.from({ length: AUTO_ADS_DAILY_LIMIT }).map((_, i) => ({
      id: `auto-${i + 1}`,
      name: `Auto Ad ${i + 1}`,
      description: 'Automated video advertisement',
      time: AUTO_ADS_INTERVAL_MS / 1000, // Time in seconds
      reward: AUTO_ADS_REWARD_POINTS,
      status: 'pending',
      image: '',
    })),
  },
];
